CREATE TABLE IF NOT EXISTS wallets (
  id SERIAL PRIMARY KEY,
  owner_id INTEGER NOT NULL,
  currency TEXT NOT NULL,
  balance NUMERIC(18,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
